#!/bin/sh
# Generated by passenger (Launch.cs) from Assets/session/session.sh; rewritten
# on every start. Every brace-delimited placeholder below is substituted by
# Launch.Plan before it is written; a survivor is a bug, and a test says so.
#
# Run from inside the compositor, which is the only place that can observe what
# actually came up: $PPID is the sway that started it, and WAYLAND_DISPLAY is
# the display sway got rather than the one anyone hoped for.

# Everything this session says about itself, including its children's. Until
# there was a log, wayvnc failing to bind and the compositor refusing to exit
# were both silent -- the session came up looking healthy and was not. Truncated
# per start, because it is the current session that is worth explaining.
exec > '{state}/session.log' 2>&1
echo "=== session starting, display $WAYLAND_DISPLAY, compositor $PPID ==="

wayvnc --render-cursor --websocket -o {output} -S '{ctl}' '{host}' '{port}' &
vnc_pid=$!

{ime}

# The host's config directory, minus the one file in it that decides what this
# browser *is*.
#
# The distribution's `google-chrome-stable` is a shell wrapper that splices
# `$XDG_CONFIG_HOME/chrome-flags.conf` into argv. That file is a human's
# personal dotfile for their own desktop -- unversioned, invisible to this side,
# and free to say anything: `--disable-gpu` in there would silently undo the
# hardware GL this session goes to some trouble to keep, and the one on the
# machine this was written on was quietly supplying `--touch-events` and the
# ozone platform this session runs on -- so on any host without that file, the
# browser fell back to X11 (ticket 061).
#
# A symlink farm rather than an empty directory, because this tool's whole
# premise is inheriting the host -- its fonts above all -- and $XDG_CONFIG_HOME
# is also where fontconfig and GTK keep theirs. Blanking it would have insulated
# Chrome from far more than the flags file. Links, so writes still land in the
# real files.
chrome_config='{state}/xdg-config'
host_config="${XDG_CONFIG_HOME:-$HOME/.config}"
rm -rf "$chrome_config" && mkdir -p "$chrome_config"
for entry in "$host_config"/* "$host_config"/.[!.]*; do
  [ -e "$entry" ] || continue                        # an unmatched glob is itself
  [ "${entry##*/}" = 'chrome-flags.conf' ] && continue
  ln -s "$entry" "$chrome_config/" || echo "could not link $entry"
done

XDG_CONFIG_HOME="$chrome_config" {chrome} &
chrome_pid=$!

printf 'compositor_pid=%s\nchrome_pid=%s\nvnc_pid=%s\nvnc_host=%s\nvnc_port=%s\nctl_socket=%s\nwayland_display=%s\n' \
  "$PPID" "$chrome_pid" "$vnc_pid" '{host}' '{port}' '{ctl}' "$WAYLAND_DISPLAY" \
  > '{record}.tmp' && mv '{record}.tmp' '{record}'

# Chrome is the session. cage exited when its child did and sway does not, so a
# dead browser would otherwise leave a live compositor holding the port -- the
# black screen this project started from, and what happened the first time this
# was tried: the human closed the window and sway stayed up.
wait "$chrome_pid"
echo "=== chrome $chrome_pid exited; stopping the compositor ==="

# Both, in this order, and both reported. `swaymsg exit` is the polite one and
# needs a socket that may not be there; the signal needs nothing at all.
swaymsg exit || echo "swaymsg exit failed ($?)"
sleep 1
kill "$PPID" 2>/dev/null || echo "kill $PPID failed ($?)"
