#!/bin/sh
# Generated by passenger (Launch.cs) from Assets/session/session.sh; rewritten
# on every start. {braces} are substituted before it is written.
#
# Run from inside the compositor, which is the only place that can observe what
# actually came up: $PPID is the sway that started it, and WAYLAND_DISPLAY is
# the display sway got rather than the one anyone hoped for.
wayvnc --render-cursor --websocket -o {output} -S '{ctl}' '{host}' '{port}' &
vnc_pid=$!

{ime}

{chrome} &
chrome_pid=$!

printf 'compositor_pid=%s\nchrome_pid=%s\nvnc_pid=%s\nvnc_host=%s\nvnc_port=%s\nctl_socket=%s\nwayland_display=%s\n' \
  "$PPID" "$chrome_pid" "$vnc_pid" '{host}' '{port}' '{ctl}' "$WAYLAND_DISPLAY" \
  > '{record}.tmp' && mv '{record}.tmp' '{record}'

# Chrome is the session. cage exited when its child did and sway does not, so a
# dead browser would otherwise leave a live compositor holding the port -- the
# black screen this project started from.
wait "$chrome_pid"
[ -n "${ime_pid:-}" ] && kill "$ime_pid" 2>/dev/null
swaymsg exit >/dev/null 2>&1 || kill "$PPID" 2>/dev/null
