// Imperative shell: how Chrome is launched so that it starts out hidden.
//
// Deliberately NOT headless: headless changes the fingerprint (no GPU, software
// WebGL, no window) and makes human handoff impossible. The window stays fully
// real -- it is just parked somewhere you aren't looking.
//
// There is no standard Wayland protocol for a window to hide itself, and the
// compositor-specific ways of doing it are unportable and prone to breaking, so
// there is exactly one real mechanism here plus a null object for when its
// dependencies are missing. Override the choice with PASSENGER_WM.
//
// Showing the browser to a human is a separate concern -- see Present.

namespace Passenger;

/// <summary>What every launch mechanism must be able to do.</summary>
public interface IWindowBackend
{
    BackendName Name { get; }

    bool Available();

    void Prepare();

    LaunchPlan Plan(IReadOnlyList<string> argv);
}

public static class Launch
{
    public const string WmClass = "passenger";

    public static string SessionSh => Path.Combine(Config.StateDir, "cage-session.sh");

    // --render-cursor draws the pointer into the frame itself. Without it the
    // cursor is left to the client to draw from a cursor sprite, and a viewer that
    // does not draw one shows no pointer at all -- unusable for the handoff this
    // window exists for, since you cannot click what you cannot see.
    //
    // --websocket because the viewer is a page rather than a native client (see
    // Present). It changes what the port speaks: a browser can reach it, and a
    // raw VNC client no longer can.
    //
    // The session record is written from inside cage because only here can the
    // real values be observed: $PPID is the cage that started this script, $$
    // survives the exec below and so is Chrome's pid, and WAYLAND_DISPLAY is the
    // display cage actually got rather than the one we hoped for.
    public const string SessionScript = """
        #!/bin/sh
        # Generated by passenger (Launch.cs); rewritten on every start.
        wayvnc --render-cursor --websocket -S '{ctl}' '{host}' '{port}' &
        vnc_pid=$!
        printf 'cage_pid=%s\nchrome_pid=%s\nvnc_pid=%s\nvnc_host=%s\nvnc_port=%s\nctl_socket=%s\nwayland_display=%s\n' \
          "$PPID" "$$" "$vnc_pid" '{host}' '{port}' '{ctl}' "$WAYLAND_DISPLAY" \
          > '{record}.tmp' && mv '{record}.tmp' '{record}'
        exec {chrome}

        """;

    /// <summary>
    /// Chrome inside its own cage compositor, viewed over VNC on demand.
    ///
    /// The host compositor is not involved, so nothing here breaks when you switch
    /// compositors -- or when one of them rewrites the IPC a backend depended on.
    /// </summary>
    public sealed class NestedBackend : IWindowBackend
    {
        public BackendName Name => BackendName.Nested;

        public bool Available() => Which("cage") is not null && Which("wayvnc") is not null;

        public void Prepare()
        {
        }

        public LaunchPlan Plan(IReadOnlyList<string> argv)
        {
            Directory.CreateDirectory(Config.StateDir);
            // Claimed per session rather than fixed: a second session that reused
            // the port would lose the bind, leaving the *stale* wayvnc serving an
            // empty compositor to anyone who connected.
            int port = Sessions.FreePort();
            string ctl = Sessions.CtlSocket(port);
            string quoted = string.Join(" ", argv.Select(a => $"'{a}'"));
            File.WriteAllText(SessionSh, SessionScript
                .Replace("{ctl}", ctl)
                .Replace("{host}", Config.Settings.VncHost)
                .Replace("{port}", port.ToString())
                .Replace("{record}", Sessions.SessionFile)
                .Replace("{chrome}", quoted));
            File.SetUnixFileMode(SessionSh,
                UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute
                | UnixFileMode.GroupRead | UnixFileMode.GroupExecute
                | UnixFileMode.OtherRead | UnixFileMode.OtherExecute);
            // Headless wlroots still renders through the GPU render node, so WebGL
            // keeps reporting the real adapter.
            return new LaunchPlan
            {
                Argv = ["cage", "--", SessionSh],
                Env = new Dictionary<string, string>
                {
                    ["WLR_BACKENDS"] = "headless",
                    ["WLR_LIBINPUT_NO_DEVICES"] = "1",
                },
            };
        }
    }

    /// <summary>No mechanism available; the window simply stays visible.</summary>
    public sealed class NoOpBackend : IWindowBackend
    {
        public BackendName Name => BackendName.None;

        public bool Available() => true;

        public void Prepare()
        {
        }

        public LaunchPlan Plan(IReadOnlyList<string> argv) => new() { Argv = argv };
    }

    private static IWindowBackend Build(BackendName name) => name switch
    {
        BackendName.Nested => new NestedBackend(),
        BackendName.None => new NoOpBackend(),
        _ => throw new ArgumentOutOfRangeException(nameof(name)),
    };

    private static readonly BackendName[] AutoOrder = [BackendName.Nested, BackendName.None];

    public static IWindowBackend Select()
    {
        string? forced = Environment.GetEnvironmentVariable("PASSENGER_WM");
        if (!string.IsNullOrEmpty(forced))
        {
            BackendName? name = EnumNames.ParseBackend(forced);
            if (name is null)
            {
                throw new WindowException(
                    ErrorCode.UnknownWindowBackend, $"unknown backend '{forced}'",
                    string.Join(", ", EnumNames.BackendNames));
            }

            return Build(name.Value);
        }

        foreach (BackendName name in AutoOrder)
        {
            IWindowBackend backend = Build(name);
            if (backend.Available())
            {
                return backend;
            }
        }

        return new NoOpBackend();
    }

    /// <summary>
    /// Where a program is on PATH, or null. `shutil.which`, which .NET has no
    /// equivalent of.
    /// </summary>
    public static string? Which(string program)
    {
        if (program.Contains('/'))
        {
            return File.Exists(program) && IsExecutable(program) ? program : null;
        }

        string path = Environment.GetEnvironmentVariable("PATH") ?? "";
        foreach (string dir in path.Split(':', StringSplitOptions.RemoveEmptyEntries))
        {
            string candidate = Path.Combine(dir, program);
            if (File.Exists(candidate) && IsExecutable(candidate))
            {
                return candidate;
            }
        }

        return null;
    }

    private static bool IsExecutable(string path)
    {
        try
        {
            UnixFileMode mode = File.GetUnixFileMode(path);
            return (mode & (UnixFileMode.UserExecute | UnixFileMode.GroupExecute
                            | UnixFileMode.OtherExecute)) != 0;
        }
        catch (Exception)
        {
            return false;
        }
    }
}
